name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - deploy/cloudfare

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 9.14.2

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with: 
          apiToken: ${{ secrets.CLOUDFLARE_ACCOUNT_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=ashwin-anil --branch=production
